---

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install sshpass and rsync
  package:
    name: ["rsync", "sshpass"]
    state: present

- name: Copy backup script to server.
  template:
    src: backup.sh.j2
    dest: "/opt/backup.sh"
    mode: 0744


- name: Configure backup cron job.
  cron:
    name: "Backup cron job"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    day: "{{ backup_day }}"
    month: "{{ backup_month }}"
    weekday: "{{ backup_weekday }}"
    job: "/opt/backup.sh"
