---
- name: Copy backup script to server.
  template:
    src: backup.sh.j2
    dest: "{{ backup_path }}/backup.sh"
    mode: 0744


- name: Configure backup cron job.
  cron:
    name: "Backup cron job"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    job: "{{ backup_path }}/backup.sh"
    state: "{{ backup_cron_job_state }}"
